### ISSUE TITLE
Trouble setting up UpSet visualisation framework locally

### ISSUE THREAD

**Issue by wowrao101** [visdesignlab/upset2#172] opened 2023-05-19 02:27 UTC
I have been trying to setup UpSet2 locally for a POC we are doing to make sure that the framework is capable to handle our data. However, I have been facing a few issues while doing it. I have setup the multinet server as suggested [here](https://github.com/visdesignlab/upset2/issues/122), and the local host seems to initialing the UpSet server, however once I login, I get “Error: invalid_request Invalid client_id parameter value”, screenshot attached below. I have gone through the rest of the issues but couldn’t find anything. Is there any definitive guide where you have summarised the entire steps to setup UpSet2 locally? Or would it be possible to just directly resolve this issue?

Any help would be really appreciated. 

<img width="1791" alt="Screenshot 2023-05-19 at 6 56 23 AM" src="https://github.com/visdesignlab/upset2/assets/122099458/84796112-d7b7-4ba4-ae0b-67c1a08a3720">

**Comment by JakeWags** [comment] 2023-06-05 17:02
Closed due to inactivity

**Comment by wowrao101** [comment] 2023-06-13 06:31
Hello, sorry for the late response. I tried completing the OAuth login setup but i still seem to get the same issue, I have restarted the server and the system with no luck. Just to clarify, one of the steps involves moving the .env.default file to .env, but I couldn't find any .env folder within the package hence I created it, is this what is expected? Thanks!

**Comment by JakeWags** [comment] 2023-06-13 16:59
> Just to clarify, one of the steps involves moving the .env.default file to .env, but I couldn't find any .env folder within the package hence I created it, is this what is expected?

Did you create a `.env` folder? This needs to be a file in the root directory of the `multinet-client` folder. The contents of the file `.env.default` should be copied into the `.env` file in the same directory.

**Comment by wowrao101** [comment] 2023-06-14 04:54
I can't find a file called .env inside the multinet-client folder, hence I created a new one and tried again, still doesn't work, another thing I noticed is that when I load the the multinet-client running on localhost:8080/, it opens up, but when I try opening a table for visualization I get the following error: 

```
Invalid URL
    at new NodeError (node:internal/errors:399:5)
    at new URL (node:internal/url:560:13)
    at viteServeRawFsMiddleware (file:///Users/vrroz/Workspace/multinet-client/node_modules/vite/dist/node/chunks/dep-3007b26d.js:39230:21)
    at call (file:///Users/vrroz/Workspace/multinet-client/node_modules/vite/dist/node/chunks/dep-3007b26d.js:47308:7)
    at next (file:///Users/vrroz/Workspace/multinet-client/node_modules/vite/dist/node/chunks/dep-3007b26d.js:47252:5)
    at viteTransformMiddleware (file:///Users/vrroz/Workspace/multinet-client/node_modules/vite/dist/node/chunks/dep-3007b26d.js:60725:9)
    at call (file:///Users/vrroz/Workspace/multinet-client/node_modules/vite/dist/node/chunks/dep-3007b26d.js:47308:7)
    at next (file:///Users/vrroz/Workspace/multinet-client/node_modules/vite/dist/node/chunks/dep-3007b26d.js:47252:5)
    at file:///Users/vrroz/Workspace/multinet-client/node_modules/vite/dist/node/chunks/dep-3007b26d.js:39123:28
    at viteServePublicMiddleware (file:///Users/vrroz/Workspace/multinet-client/node_modules/vite/dist/node/chunks/dep-3007b26d.js:39173:9
```

**Comment by JakeWags** [comment] 2023-06-14 17:44
If you are able to access the multinet client at port 8080, then that seems to be working. Step 4 of the Multinet-Client installation is:
> Copy the default application registry (yarn init-appregistry)
>>If running the visualization applications locally, update these values in src/assets/appregistry.json

Are you able to go to `localhost:3000` to access UpSet?

**Comment by wowrao101** [comment] 2023-06-14 19:01
Yes, it shows the login page, and when I enter the user and password, it goes to the page as displayed above, the page where it shows ```Error: invalid_request Invalid client_id parameter value```, I have set the ```app-registry.json``` file as follows: 
```
 "table_visualizations": [
        {
            "name": "Upset",
            "url": "localhost:3000/"
        }
    ]
```

And left the rest as is. The instructions were not very clear for setup [here (4th Step)](https://github.com/multinet-app/multinet-client).

**Comment by wowrao101** [comment] 2023-06-14 20:42
```yarn init-appregistry``` seems to be failing, is this the right command? And where do I execute it from? The multinet root folder or from the assets folder where appregistry.json file is present?

**Comment by bssatya** [comment] 2023-06-18 10:19
Hello Jake, I and [wowrao101](https://github.com/wowrao101) work in the same team. We have been having challenges in setting up UpSet locally and build POC with our data. Is there a possibility to connect over a call and resolve the problems we are facing?

**Comment by bssatya** [comment] 2023-06-18 13:49
I was able to identify the root cause of the problem and access the upset2 UI (localhost:3000).
The problem is UpSet UI is sending a client-id which is hard coded in /upset2/packages/app/src/atoms/authAtoms.ts file. Once I updated the client-id with the id generated in 'Django OAuth Toolkit' from Multinet Administration page when new app is created as part of multinet-app setup.

**Comment by JakeWags** [comment] 2023-06-20 22:03
@bssatya I somehow completely spaced the authAtom file. It looks to me like the framework is in place to use a .env file configuration. This would be consistent with the other multinet apps (see [multimatrix](https://github.com/multinet-app/multimatrix)).
I will be updating the local installation documentation/process to reflect the actual steps required to deploy upset locally with the multinet infrastructure. See draft PR: #193 
I'll close this issue when that merges in unless you and @wowrao101 are still having problems.

**Closed** 2023-07-17 18:41 UTC
